<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <AssemblyName>NightCallDumper</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <LibsDir>$(MSBuildThisFileDirectory)..\..\ref-russian\libs</LibsDir>
    <BepInExDir>$(MSBuildThisFileDirectory)..\..\ref-russian\data\BepInEx\core</BepInExDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(BepInExDir)\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(LibsDir)\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(LibsDir)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputModule"><HintPath>D:\SteamLibrary\steamapps\common\Night Call\Night Call_Data\Managed\UnityEngine.InputModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
